import gradio as gr
from particleanalyzer.core.about import (
    about_ru,
    about_en,
    about_zh_cn,
    about_zh_tw,
)
from particleanalyzer.core.parameter_information import (
    reference_ru,
    reference_en,
    reference_zh_cn,
    reference_zh_tw,
)

translations = {
    "ru": {
        "Подготовка...": "Подготовка...",
        "Загрузка изображения...": "Загрузка изображения...",
        "Instrument scale in µm": "Instrument scale in µm",
        "Pixels": "Pixels",
        "Original": "Original",
        "YOLO обрабатывает изображение...": "YOLO обрабатывает изображение...",
        "Ошибка: недостаточно памяти CUDA. Освобождаем память. Попробуйте уменьшить разрешение изображения или включите режим SAHI...": "Ошибка: недостаточно памяти CUDA. Освобождаем память. Попробуйте уменьшить разрешение изображения или включите режим SAHI...",
        "Произошла другая ошибка": "Произошла другая ошибка",
        "Объекты не обнаружены.": "Объекты не обнаружены.",
        "Достигнут предел количества обнаружений. Увеличьте максимальное количество обнаружений в настройках.": "Достигнут предел количества обнаружений. Увеличьте максимальное количество обнаружений в настройках.",
        "Обработка частиц...": "Обработка частиц...",
        "мкм": "мкм",
        "нм": "нм",
        "пикс": "пикс",
        "ед.": "ед.",
        "Диаметр": "Диаметр",
        "Средний диаметр": "Средний диаметр",
        "Максимальный диаметр": "Максимальный диаметр",
        "Минимальный диаметр": "Минимальный диаметр",
        "Максимальный угол": "Максимальный угол",
        "Минимальный угол": "Минимальный угол",
        "Площадь": "Площадь",
        "Периметр": "Периметр",
        "Detectron2 обрабатывает изображение...": "Detectron2 обрабатывает изображение...",
        "Произошла ошибка:": "Произошла ошибка:",
        "SAHI обрабатывает изображение...": "SAHI обрабатывает изображение...",
        "Построение таблицы...": "Построение таблицы...",
        "Параметр": "Параметр",
        "Среднее": "Среднее",
        "Медиана": "Медиана",
        "Максимум": "Максимум",
        "Минимум": "Минимум",
        "СО": "СО",
        "Построение графиков...": "Построение графиков...",
        "Распределение площади": "Распределение площади",
        "Распределение периметра": "Распределение периметра",
        "Распределение диаметра": "Распределение диаметра",
        "Распределение эксцентриситета": "Распределение эксцентриситета",
        "Распределение интенсивности": "Распределение интенсивности",
        "(норм. распр.)": "(норм. распр.)",
        "Количество": "Количество",
        "Плотность вероятности": "Плотность вероятности",
        "Эксцентриситет": "Эксцентриситет",
        "Интенсивность": "Интенсивность",
        "Критическая ошибка в process_image": "Критическая ошибка в process_image",
        "Критическая ошибка": "Критическая ошибка",
        "Ошибка в вычислении центроида.": "Ошибка в вычислении центроида.",
        "Найдено больше двух точек.": "Найдено больше двух точек.",
        "Обозначьте на изображении масштабную шкалу при помощи двух точек.": "Обозначьте на изображении масштабную шкалу при помощи двух точек.",
        "Тёмный режим": "Тёмный режим",
        "Светлый режим": "Светлый режим",
        "ParticleAnalyzer — Инструмент для анализа изображений SEM": "ParticleAnalyzer — Инструмент для анализа изображений SEM",
        "Инструмент для анализа размерных характеристик частиц на изображениях SEM.<br>В случае проблем с сегментацией изображения или возникновения ошибок, пожалуйста, направляйте материалы на электронную почту: rybakov-ks@ya.ru": "Инструмент для анализа размерных характеристик частиц на изображениях SEM.<br>В случае проблем с сегментацией изображения или возникновения ошибок, пожалуйста, направляйте материалы на электронную почту: rybakov-ks@ya.ru",
        "Анализ": "Анализ",
        "Изображение СЭМ": "Изображение СЭМ",
        "Результат сегментации": "Результат сегментации",
        "Примеры": "Примеры",
        "Характеристики частицы": "Характеристики частицы",
        "Анализировать": "Анализировать",
        "Очистить": "Очистить",
        "Количество частиц": "Количество частиц",
        "Статистика по частицам": "Статистика по частицам",
        "Характеристики частиц": "Характеристики частиц",
        "Файлы для скачивания": "Файлы для скачивания",
        "Графики распределения": "Графики распределения",
        "Вы удовлетворены качеством сегментации?": "Вы удовлетворены качеством сегментации?",
        "Да": "Да",
        "Нет": "Нет",
        "Настройки": "Настройки",
        "Модель обнаружения": "Модель обнаружения",
        "Включить": "Включить",
        "Включить обработку с разбиением на фрагменты (SAHI)?": "Включить обработку с разбиением на фрагменты (SAHI)?",
        "Высота слайса": "Высота слайса",
        "Ширина слайса": "Ширина слайса",
        "Перекрытие по высоте": "Перекрытие по высоте",
        "Перекрытие по ширине": "Перекрытие по ширине",
        "Точность обнаружения": "Точность обнаружения",
        "Порог перекрытия (IoU)": "Порог перекрытия (IoU)",
        "Максимальное количество обнаружений": "Максимальное количество обнаружений",
        "Режим масштабирования": "Режим масштабирования",
        "Разрешение изображения": "Разрешение изображения",
        "Округлять результаты до": "Округлять результаты до",
        "Включить режим анализа отдельных частиц?": "Включить режим анализа отдельных частиц?",
        "Интервалов на гистограмме": "Интервалов на гистограмме",
        "Ошибка: изображение отсутствует...": "Ошибка: изображение отсутствует...",
        "Используется CUDA устройство:": "Используется CUDA устройство:",
        "CUDA не доступна, используется CPU": "CUDA не доступна, используется CPU",
        "Шкала прибора в мкм": "Instrument scale in µm",
        "Включить отображение диаметров Ферета?": "Включить отображение диаметров Ферета?",
        "Распределение диаметра Ферета": "Распределение диаметра Ферета",
        "Распределение угла Ферета": "Распределение угла Ферета",
        "Векторное поле ориентации": "Векторное поле ориентации",
        "Удлинение": "Удлинение",
        "Утолщение": "Утолщение",
        "ИИ-интерпретация SEM-данных": "ИИ-интерпретация SEM-данных",
        "Запустить ИИ-анализ": "Запустить ИИ-анализ",
        "Языковая модель (LLM)": "Языковая модель (LLM)",
        "Готово!": "Готово!",
        "Длина шкалы в мкм": "Длина шкалы в мкм",
        "Длина шкалы в нм": "Длина шкалы в нм",
        "О программе": "О программе",
        "Статистика": "Статистика",
        "Графики": "Графики",
        "ИИ-анализ": "ИИ-анализ",
        "Файлы": "Файлы",
        "Оценить результаты": "Оценить результаты",
        "Результаты сегментации частиц": "Результаты сегментации частиц",
        "Отменить": "Отменить",
        about_ru: about_ru,
        "ru": "'ru'",
        "Помощь": "Помощь",
        "Как задать масштаб?": "Как задать масштаб?",
        "Справочник параметров": "Справочник параметров",
        reference_ru: reference_ru,
        """🔬 **Добро пожаловать в систему анализа SEM-изображений!**
        Я – ваш виртуальный ассистент в сканирующей электронной микроскопии. Готов провести детальный анализ морфологии и размерных характеристик частиц.""": """🔬 **Добро пожаловать в систему анализа SEM-изображений!**
            Я – ваш виртуальный ассистент в сканирующей электронной микроскопии. Готов провести детальный анализ морфологии и размерных характеристик частиц.""",
        "Видео инструкция": "Видео инструкция",
        "Параметры фильтрации": "Параметры фильтрации",
        "Включить контур?": "Включить контур?",
        "Цвет контура": "Цвет контура",
        "Включить заливку?": "Включить заливку?",
        "Тип заливки": "Тип заливки",
        "Цвет заливки": "Цвет заливки",
        "Прозрачность заливки": "Прозрачность заливки",
        "Удалить частицы": "Удалить частицы",
        "Сбросить таблицу": "Сбросить таблицу",
        "Загрузить изображение СЭМ": "Загрузить изображение СЭМ",
        "Статус калибровки масштаба": "Статус калибровки масштаба",
        "Выберите две крайние точки на шкале": "Выберите две крайние точки на шкале",
        "Расстояние равно": "Расстояние равно",
        "пикселей": "пикселей",
        "Выбрано точек": "Выбрано точек",
        "Ориентация": "Ориентация",
        "Количество обнаружений": "Количество обнаружений",
        "Настройки обнаружения": "Настройки обнаружения",
        "Обработка с разбиением (SAHI)": "Обработка с разбиением (SAHI)",
        "Основные параметры": "Основные параметры",
        "Параметры визуализации": "Параметры визуализации",
        "Не поддерживаемый формат изображения.": "Не поддерживаемый формат изображения.",
        "Включить отображение масштабной шкалы?": "Включить отображение масштабной шкалы?",
        "Улучшение изображения": "Улучшение изображения",
        "RF-DETR обрабатывает изображение...": "RF-DETR обрабатывает изображение...",
        "Автоматическое определение масштабной шкалы не удалось. Укажите шкалу вручную или продолжите анализ в пикселях.": "Автоматическое определение масштабной шкалы не удалось. Укажите шкалу вручную или продолжите анализ в пикселях.",
        "Масштабная шкала обнаружена и распознана автоматически. Можно продолжить дальнейший анализ.": "Масштабная шкала обнаружена и распознана автоматически. Можно продолжить дальнейший анализ.",
        "Включить автоматическое определение масштабной шкалы?": "Включить автоматическое определение масштабной шкалы?",
        "2D shape filtering": "Фильтрация формы (2D)",
        "Keep near-circular particles only": "Оставлять только округлые частицы",
        "Uses circularity and axis ratio as a 2D proxy for sphericity.": "Использует округлость и отношение осей как 2D-аппроксимацию сферичности.",
        "Minimum circularity": "Минимальная округлость",
        "Minimum axis ratio (minor/major)": "Минимальное отношение осей (малая/большая)",
        "No particles matched the 2D shape filter. Lower the thresholds or disable the filter.": "Ни одна частица не прошла 2D-фильтр формы. Снизьте пороги или отключите фильтр.",
        "Analyze nanorods": "Анализировать наностержни",
        "Measures rod length and width with orthogonal Feret calipers. Nanorod mode overrides the near-circular filter.": "Измеряет длину и ширину стержня ортогональными калиперами Ферета. Режим наностержней имеет приоритет над фильтром округлых частиц.",
        "Minimum nanorod aspect ratio (L/W)": "Минимальное отношение сторон наностержня (L/W)",
        "Length is the caliper span perpendicular to the minimum Feret width.": "Длина — размах калипера, перпендикулярный минимальной ширине Ферета.",
        "Exclude border-touching rods": "Исключать стержни, касающиеся границы",
        "Recommended because clipped rods bias aspect-ratio statistics.": "Рекомендуется, поскольку обрезанные стержни искажают статистику отношения сторон.",
        "Border quality control": "Контроль качества границ",
        "Exclude border-touching particles": "Исключать частицы, касающиеся границы",
        "Applied independently of shape mode. Border-clipped particles bias size and aspect-ratio measurements.": "Применяется независимо от режима анализа формы. Обрезанные границей частицы искажают измерения размера и отношения сторон.",
        "Manual contour editor": "Ручной редактор контуров",
        "Select a particle in the segmentation result before replacing or deleting it. For add or replace, click polygon vertices in order, then apply the contour.": "Перед заменой или удалением выберите частицу на результате сегментации. Для добавления или замены последовательно укажите вершины полигона, затем примените контур.",
        "Choose Add or Replace to begin drawing.": "Выберите «Добавить» или «Заменить», чтобы начать рисование.",
        "Contour editing canvas": "Полотно редактирования контура",
        "Add new contour": "Добавить новый контур",
        "Replace selected contour": "Заменить выбранный контур",
        "Delete selected particles": "Удалить выбранные частицы",
        "Select at least one particle before deleting.": "Перед удалением выберите хотя бы одну частицу.",
        "Undo last point": "Отменить последнюю точку",
        "Clear draft": "Очистить черновик",
        "Apply contour": "Применить контур",
        "Run image analysis before editing contours.": "Перед редактированием контуров выполните анализ изображения.",
        "Select exactly one particle before replacing its contour.": "Перед заменой контура выберите ровно одну частицу.",
        "Click contour vertices in order, then choose Apply contour.": "Последовательно укажите вершины контура, затем нажмите «Применить контур».",
        "Choose Add or Replace before drawing.": "Перед рисованием выберите «Добавить» или «Заменить».",
        "Choose Add or Replace before applying a contour.": "Перед применением контура выберите «Добавить» или «Заменить».",
        "The selected point is outside the analysis image.": "Выбранная точка находится за пределами анализируемого изображения.",
        "Draft vertices: {count}": "Вершин в черновике: {count}",
        "Draft cleared.": "Черновик очищен.",
        "The contour touches the image border and was not applied because border exclusion is enabled.": "Контур касается границы изображения и не применён, поскольку включено исключение граничных частиц.",
        "The contour could not be measured.": "Не удалось измерить контур.",
        "A new contour was added and measured.": "Новый контур добавлен и измерен.",
        "The selected contour was replaced and remeasured.": "Выбранный контур заменён и повторно измерен.",
        "Exclude likely merged/overlapping rods": "Исключать вероятно слипшиеся/перекрывающиеся стержни",
        "Removes duplicate masks and oversized clusters while retaining smaller rod-like masks. Obscured rods are not reconstructed.": "Удаляет дублирующиеся маски и слишком крупные кластеры, сохраняя меньшие стержнеобразные маски. Скрытые стержни не восстанавливаются.",
        "Excluded {count} likely merged or duplicate rod masks.": "Исключено вероятно слипшихся или дублирующихся масок стержней: {count}.",
        "Overlap quality control": "Контроль качества перекрытий",
        "Exclude likely merged/duplicate masks": "Исключать вероятно объединённые/дублирующиеся маски",
        "Applied independently of shape mode. Removes duplicate masks and unusually wide or irregular clusters; hidden particles are not reconstructed.": "Применяется независимо от режима анализа формы. Удаляет дублирующиеся маски и необычно широкие или неправильные кластеры; скрытые частицы не восстанавливаются.",
        "Excluded {count} likely merged or duplicate masks.": "Исключено вероятно объединённых или дублирующихся масок: {count}.",
        "No particles remained after overlap quality control. Disable overlap exclusion to inspect ambiguous masks.": "После контроля перекрытий частиц не осталось. Отключите исключение перекрытий, чтобы проверить неоднозначные маски.",
        "Overlap QC reached its comparison limit; some ambiguous masks may remain.": "Достигнут предел сравнений при проверке перекрытий; некоторые неоднозначные маски могут остаться.",
        "No nanorods matched the selected aspect-ratio and quality criteria. Lower the threshold or allow border-touching/merged rods.": "Ни один наностержень не прошёл выбранные критерии отношения сторон и качества. Снизьте порог либо разрешите стержни у границы и вероятно слипшиеся маски.",
        "Nanorod aspect ratio (L/W)": "Отношение сторон наностержня (L/W)",
        "ISO Feret ratio (min/max)": "Отношение Ферета ISO (мин/макс)",
        "Nanorod aspect ratio (L/W) distribution": "Распределение отношения сторон наностержней (L/W)",
        "ISO Feret ratio (min/max) distribution": "Распределение отношения Ферета ISO (мин/макс)",
        "Nanorod aspect-ratio chart": "Диаграмма отношения сторон наностержней",
        "Aspect-ratio distribution": "Распределение отношения сторон",
        "Rod length versus width": "Длина наностержня в зависимости от ширины",
        "Retained rods": "Сохранённые наностержни",
        "Individual rods": "Отдельные наностержни",
        "Interior rods": "Внутренние наностержни",
        "Border-touching rods": "Наностержни у границы",
        "Unknown border status": "Неизвестный статус границы",
        "Particle": "Частица",
        "Rod orientation": "Ориентация наностержня",
        "Not available": "Нет данных",
        "Border touching": "Касание границы",
        "Count": "Количество",
        "Mean": "Среднее",
        "Median": "Медиана",
        "Minimum L/W": "Минимальное L/W",
        "Invalid rows": "Недопустимые строки",
        "No nanorod measurements available.": "Нет доступных измерений наностержней.",
        "Projected aspect ratio = orthogonal-caliper length / minimum-Feret width; it is dimensionless and describes a 2D projection.": "Проекционное отношение сторон = длина по ортогональному калиперу / минимальная ширина Ферета; величина безразмерна и описывает 2D-проекцию.",
        "Language settings": "Настройки языка",
        "Interface language": "Язык интерфейса",
        "Switches interface labels and future analysis results. The page reloads.": "Переключает язык интерфейса и последующих результатов анализа. Страница перезагрузится.",
        "Automatic / Browser": "Автоматически / Браузер",
        "No particles detected": "Частицы не обнаружены",
        "Analysis error": "Ошибка анализа",
    },
    "en": {
        "Подготовка...": "Initializing...",
        "Загрузка изображения...": "Loading image...",
        "Instrument scale in µm": "Instrument scale in µm",
        "Pixels": "Pixels",
        "Оригинал": "Original",
        "YOLO обрабатывает изображение...": "YOLO is processing image...",
        "Ошибка: недостаточно памяти CUDA. Освобождаем память. Попробуйте уменьшить разрешение изображения или включите режим SAHI...": "Error: Not enough CUDA memory. Freeing up memory. Please try reducing the image resolution or enable SAHI mode...",
        "Произошла другая ошибка": "An error occurred",
        "Объекты не обнаружены.": "No objects detected.",
        "Достигнут предел количества обнаружений. Увеличьте максимальное количество обнаружений в настройках.": "Detection limit reached. Increase maximum detections in settings.",
        "Обработка частиц...": "Processing particles...",
        "ед.": "units",
        "мкм": "µm",
        "нм": "nm",
        "пикс": "px",
        "Диаметр": "Diameter",
        "Средний диаметр": "Average diameter",
        "Максимальный диаметр": "Maximum diameter",
        "Минимальный диаметр": "Minimum diameter",
        "Максимальный угол": "Maximum angle",
        "Минимальный угол": "Minimum angle",
        "Площадь": "Area",
        "Периметр": "Perimeter",
        "Detectron2 обрабатывает изображение...": "Detectron2 is processing images...",
        "Произошла ошибка:": "Error occurred:",
        "SAHI обрабатывает изображение...": "SAHI is processing the image...",
        "Построение таблицы...": "Generating table...",
        "Параметр": "Parameter",
        "Среднее": "Average",
        "Медиана": "Median",
        "Максимум": "Maximum",
        "Минимум": "Minimum",
        "СО": "SD",
        "Построение графиков...": "Generating plots...",
        "Распределение площади": "Area distribution",
        "Распределение периметра": "Perimeter distribution",
        "Распределение диаметра": "Diameter distribution",
        "Распределение эксцентриситета": "Eccentricity distribution",
        "Распределение интенсивности": "Intensity distribution",
        "(норм. распр.)": "(normal distribution)",
        "Количество": "Count",
        "Плотность вероятности": "Probability density",
        "Эксцентриситет": "Eccentricity",
        "Интенсивность": "Intensity",
        "Критическая ошибка в process_image": "Critical error in process_image",
        "Критическая ошибка": "Critical error",
        "Ошибка в вычислении центроида.": "Error in centroid calculation.",
        "Найдено больше двух точек.": "More than two points found.",
        "Обозначьте на изображении масштабную шкалу при помощи двух точек.": "Please mark the scale bar on the image using two points.",
        "Тёмный режим": "Dark mode",
        "Светлый режим": "Light mode",
        "ParticleAnalyzer — Инструмент для анализа изображений SEM": "ParticleAnalyzer — SEM Image Analysis Tool",
        "Инструмент для анализа размерных характеристик частиц на изображениях SEM.<br>В случае проблем с сегментацией изображения или возникновения ошибок, пожалуйста, направляйте материалы на электронную почту: rybakov-ks@ya.ru": "This tool can be used to analyze particle size characteristics in SEM images.<br>In case of problems with image segmentation or errors, please send materials to e-mail: rybakov-ks@ya.ru",
        "Анализ": "Analysis",
        "Изображение СЭМ": "SEM Image",
        "Результат сегментации": "Segmentation result",
        "Примеры": "Examples",
        "Характеристики частицы": "Particle characteristics",
        "Анализировать": "Analyze",
        "Очистить": "Clear",
        "Количество частиц": "Particle count",
        "Статистика по частицам": "Particle statistics",
        "Характеристики частиц": "Particles characteristics",
        "Файлы для скачивания": "Downloadable files",
        "Графики распределения": "Distribution plots",
        "Вы удовлетворены качеством сегментации?": "Are you satisfied with the segmentation quality?",
        "Да": "Yes",
        "Нет": "No",
        "Настройки": "Settings",
        "Модель обнаружения": "Detection model",
        "Включить": "Enable",
        "Включить обработку с разбиением на фрагменты (SAHI)?": "Enable tiled processing (SAHI)?",
        "Высота слайса": "Slice height",
        "Ширина слайса": "Slice width",
        "Перекрытие по высоте": "Height overlap ratio",
        "Перекрытие по ширине": "Width overlap ratio",
        "Точность обнаружения": "Detection confidence threshold",
        "Порог перекрытия (IoU)": "IoU threshold",
        "Максимальное количество обнаружений": "Maximum detections",
        "Режим масштабирования": "Scaling mode",
        "Разрешение изображения": "Image resolution",
        "Округлять результаты до": "Round values to",
        "Включить режим анализа отдельных частиц?": "Enable single particle analysis mode?",
        "Интервалов на гистограмме": "Number of histogram bins",
        "Ошибка: изображение отсутствует...": "Error: Image is missing...",
        "Используется CUDA устройство:": "CUDA device in use:",
        "CUDA не доступна, используется CPU": "CUDA not available, using CPU",
        "Шкала прибора в мкм": "Instrument scale in µm",
        "Включить отображение диаметров Ферета?": "Enable display of ferret diameters?",
        "Распределение диаметра Ферета": "Distribution of Feret diameter",
        "Распределение угла Ферета": "Distribution of Feret's angle",
        "Векторное поле ориентации": "Orientation Vector Field",
        "Удлинение": "Elongation",
        "Утолщение": "Thickening",
        "ИИ-интерпретация SEM-данных": "AI Interpretation of SEM Data",
        "Запустить ИИ-анализ": "Launch AI analysis",
        "Языковая модель (LLM)": "Language Model (LLM)",
        "Готово!": "Ready!",
        "Длина шкалы в мкм": "Scale length in µm",
        "Длина шкалы в нм": "Scale length in nm",
        "О программе": "About",
        "Статистика": "Statistics",
        "Графики": "Charts",
        "ИИ-анализ": "AI Analysis",
        "Файлы": "Files",
        "Оценить результаты": "Evaluate Results",
        "Результаты сегментации частиц": "Particle Segmentation Results",
        "Отменить": "Cancel",
        about_ru: about_en,
        "ru": "'en'",
        "Помощь": "Show Guide",
        "Как задать масштаб?": "How to set the scale?",
        "Справочник параметров": "Parameters Reference",
        reference_ru: reference_en,
        """🔬 **Добро пожаловать в систему анализа SEM-изображений!**
        Я – ваш виртуальный ассистент в сканирующей электронной микроскопии. Готов провести детальный анализ морфологии и размерных характеристик частиц.""": """🔬 **Welcome to the SEM Image Analysis System!**
            I am your virtual assistant for scanning electron microscopy. Ready to perform detailed analysis of particle morphology and size characteristics.""",
        "Видео инструкция": "Video instructions",
        "Параметры фильтрации": "Filtering Options",
        "Включить контур?": "Enable outline?",
        "Цвет контура": "Outline color",
        "Включить заливку?": "Enable fill?",
        "Тип заливки": "Fill Type",
        "Цвет заливки": "Fill Color",
        "Прозрачность заливки": "Fill Transparency",
        "Удалить частицы": "Remove particles",
        "Сбросить таблицу": "Reset table",
        "Загрузить изображение СЭМ": "Upload SEM image",
        "Статус калибровки масштаба": "Scale calibration status",
        "Выберите две крайние точки на шкале": "Select the two extreme points of the scale.",
        "Расстояние равно": "Distance is",
        "пикселей": "pixels",
        "Выбрано точек": "Points selected",
        "Ориентация": "Orientation",
        "Количество обнаружений": "Number of detections",
        "Настройки обнаружения": "Discovery Settings",
        "Обработка с разбиением (SAHI)": "Split processing (SAHI)",
        "Основные параметры": "Basic parameters",
        "Параметры визуализации": "Visualization Parameters",
        "Не поддерживаемый формат изображения.": "Unsupported image format.",
        "Включить отображение масштабной шкалы?": "Enable display of scale bar?",
        "Улучшение изображения": "Image enhancement",
        "RF-DETR обрабатывает изображение...": "RF-DETR processes the image...",
        "Автоматическое определение масштабной шкалы не удалось. Укажите шкалу вручную или продолжите анализ в пикселях.": "Automatic scale detection failed. Please specify the scale manually or continue the analysis in pixels.",
        "Масштабная шкала обнаружена и распознана автоматически. Можно продолжить дальнейший анализ.": "The scale bar has been detected and recognized automatically. Further analysis can proceed.",
        "Включить автоматическое определение масштабной шкалы?": "Enable automatic scale detection?",
        "2D shape filtering": "2D shape filtering",
        "Keep near-circular particles only": "Keep near-circular particles only",
        "Uses circularity and axis ratio as a 2D proxy for sphericity.": "Uses circularity and axis ratio as a 2D proxy for sphericity.",
        "Minimum circularity": "Minimum circularity",
        "Minimum axis ratio (minor/major)": "Minimum axis ratio (minor/major)",
        "No particles matched the 2D shape filter. Lower the thresholds or disable the filter.": "No particles matched the 2D shape filter. Lower the thresholds or disable the filter.",
        "Analyze nanorods": "Analyze nanorods",
        "Measures rod length and width with orthogonal Feret calipers. Nanorod mode overrides the near-circular filter.": "Measures rod length and width with orthogonal Feret calipers. Nanorod mode overrides the near-circular filter.",
        "Minimum nanorod aspect ratio (L/W)": "Minimum nanorod aspect ratio (L/W)",
        "Length is the caliper span perpendicular to the minimum Feret width.": "Length is the caliper span perpendicular to the minimum Feret width.",
        "Exclude border-touching rods": "Exclude border-touching rods",
        "Recommended because clipped rods bias aspect-ratio statistics.": "Recommended because clipped rods bias aspect-ratio statistics.",
        "Border quality control": "Border quality control",
        "Exclude border-touching particles": "Exclude border-touching particles",
        "Applied independently of shape mode. Border-clipped particles bias size and aspect-ratio measurements.": "Applied independently of shape mode. Border-clipped particles bias size and aspect-ratio measurements.",
        "Manual contour editor": "Manual contour editor",
        "Select a particle in the segmentation result before replacing or deleting it. For add or replace, click polygon vertices in order, then apply the contour.": "Select a particle in the segmentation result before replacing or deleting it. For add or replace, click polygon vertices in order, then apply the contour.",
        "Choose Add or Replace to begin drawing.": "Choose Add or Replace to begin drawing.",
        "Contour editing canvas": "Contour editing canvas",
        "Add new contour": "Add new contour",
        "Replace selected contour": "Replace selected contour",
        "Delete selected particles": "Delete selected particles",
        "Select at least one particle before deleting.": "Select at least one particle before deleting.",
        "Undo last point": "Undo last point",
        "Clear draft": "Clear draft",
        "Apply contour": "Apply contour",
        "Run image analysis before editing contours.": "Run image analysis before editing contours.",
        "Select exactly one particle before replacing its contour.": "Select exactly one particle before replacing its contour.",
        "Click contour vertices in order, then choose Apply contour.": "Click contour vertices in order, then choose Apply contour.",
        "Choose Add or Replace before drawing.": "Choose Add or Replace before drawing.",
        "Choose Add or Replace before applying a contour.": "Choose Add or Replace before applying a contour.",
        "The selected point is outside the analysis image.": "The selected point is outside the analysis image.",
        "Draft vertices: {count}": "Draft vertices: {count}",
        "Draft cleared.": "Draft cleared.",
        "The contour touches the image border and was not applied because border exclusion is enabled.": "The contour touches the image border and was not applied because border exclusion is enabled.",
        "The contour could not be measured.": "The contour could not be measured.",
        "A new contour was added and measured.": "A new contour was added and measured.",
        "The selected contour was replaced and remeasured.": "The selected contour was replaced and remeasured.",
        "Exclude likely merged/overlapping rods": "Exclude likely merged/overlapping rods",
        "Removes duplicate masks and oversized clusters while retaining smaller rod-like masks. Obscured rods are not reconstructed.": "Removes duplicate masks and oversized clusters while retaining smaller rod-like masks. Obscured rods are not reconstructed.",
        "Excluded {count} likely merged or duplicate rod masks.": "Excluded {count} likely merged or duplicate rod masks.",
        "Overlap quality control": "Overlap quality control",
        "Exclude likely merged/duplicate masks": "Exclude likely merged/duplicate masks",
        "Applied independently of shape mode. Removes duplicate masks and unusually wide or irregular clusters; hidden particles are not reconstructed.": "Applied independently of shape mode. Removes duplicate masks and unusually wide or irregular clusters; hidden particles are not reconstructed.",
        "Excluded {count} likely merged or duplicate masks.": "Excluded {count} likely merged or duplicate masks.",
        "No particles remained after overlap quality control. Disable overlap exclusion to inspect ambiguous masks.": "No particles remained after overlap quality control. Disable overlap exclusion to inspect ambiguous masks.",
        "Overlap QC reached its comparison limit; some ambiguous masks may remain.": "Overlap QC reached its comparison limit; some ambiguous masks may remain.",
        "No nanorods matched the selected aspect-ratio and quality criteria. Lower the threshold or allow border-touching/merged rods.": "No nanorods matched the selected aspect-ratio and quality criteria. Lower the threshold or allow border-touching/merged rods.",
        "Nanorod aspect ratio (L/W)": "Nanorod aspect ratio (L/W)",
        "ISO Feret ratio (min/max)": "ISO Feret ratio (min/max)",
        "Nanorod aspect ratio (L/W) distribution": "Nanorod aspect ratio (L/W) distribution",
        "ISO Feret ratio (min/max) distribution": "ISO Feret ratio (min/max) distribution",
        "Nanorod aspect-ratio chart": "Nanorod aspect-ratio chart",
        "Aspect-ratio distribution": "Aspect-ratio distribution",
        "Rod length versus width": "Rod length versus width",
        "Retained rods": "Retained rods",
        "Individual rods": "Individual rods",
        "Interior rods": "Interior rods",
        "Border-touching rods": "Border-touching rods",
        "Unknown border status": "Unknown border status",
        "Particle": "Particle",
        "Rod orientation": "Rod orientation",
        "Not available": "Not available",
        "Border touching": "Border touching",
        "Count": "Count",
        "Mean": "Mean",
        "Median": "Median",
        "Minimum L/W": "Minimum L/W",
        "Invalid rows": "Invalid rows",
        "No nanorod measurements available.": "No nanorod measurements available.",
        "Projected aspect ratio = orthogonal-caliper length / minimum-Feret width; it is dimensionless and describes a 2D projection.": "Projected aspect ratio = orthogonal-caliper length / minimum-Feret width; it is dimensionless and describes a 2D projection.",
        "Language settings": "Language settings",
        "Interface language": "Interface language",
        "Switches interface labels and future analysis results. The page reloads.": "Switches interface labels and future analysis results. The page reloads.",
        "Automatic / Browser": "Automatic / Browser",
        "No particles detected": "No particles detected",
        "Analysis error": "Analysis error",
    },
    "zh-cn": {
        "Подготовка...": "初始化中...",
        "Загрузка изображения...": "正在加载图像...",
        "Instrument scale in µm": "Instrument scale in µm",
        "Pixels": "Pixels",
        "Original": "Original",
        "YOLO обрабатывает изображение...": "YOLO正在处理图像...",
        "Ошибка: недостаточно памяти CUDA. Освобождаем память. Попробуйте уменьшить разрешение изображения или включите режим SAHI...": "错误：CUDA内存不足。正在释放内存。请尝试降低图像分辨率或启用SAHI模式...",
        "Произошла другая ошибка": "发生其他错误",
        "Объекты не обнаружены.": "未检测到对象",
        "Достигнут предел количества обнаружений. Увеличьте максимальное количество обнаружений в настройках.": "达到检测数量上限。请在设置中增加最大检测数量",
        "Обработка частиц...": "正在处理粒子...",
        "мкм": "微米",
        "нм": "纳米",
        "пикс": "像素",
        "ед.": "单位",
        "Диаметр": "直径",
        "Средний диаметр": "平均直径",
        "Максимальный диаметр": "最大直径",
        "Минимальный диаметр": "最小直径",
        "Максимальный угол": "最大角度",
        "Минимальный угол": "最小角度",
        "Площадь": "面积",
        "Периметр": "周长",
        "Detectron2 обрабатывает изображение...": "Detectron2正在处理图像...",
        "Произошла ошибка:": "发生错误:",
        "SAHI обрабатывает изображение...": "SAHI 正在处理图像...",
        "Построение таблицы...": "正在生成表格...",
        "Параметр": "参数",
        "Среднее": "平均值",
        "Медиана": "中位数",
        "Максимум": "最大值",
        "Минимум": "最小值",
        "СО": "标准差",
        "Построение графиков...": "正在生成图表...",
        "Распределение площади": "面积分布",
        "Распределение периметра": "周长分布",
        "Распределение диаметра": "直径分布",
        "Распределение эксцентриситета": "偏心率分布",
        "Распределение интенсивности": "强度分布",
        "(норм. распр.)": "(正态分布)",
        "Количество": "数量",
        "Плотность вероятности": "概率密度",
        "Эксцентриситет": "偏心率",
        "Интенсивность": "强度",
        "Критическая ошибка в process_image": "process_image中的关键错误",
        "Критическая ошибка": "严重错误",
        "Ошибка в вычислении центроида.": "计算质心时出错",
        "Найдено больше двух точек.": "找到超过两个点",
        "Обозначьте на изображении масштабную шкалу при помощи двух точек.": "请在图像上用两点标记比例尺",
        "Тёмный режим": "暗黑模式",
        "Светлый режим": "明亮模式",
        "ParticleAnalyzer — Инструмент для анализа изображений SEM": "ParticleAnalyzer — SEM图像分析工具",
        "Инструмент для анализа размерных характеристик частиц на изображениях SEM.<br>В случае проблем с сегментацией изображения или возникновения ошибок, пожалуйста, направляйте материалы на электронную почту: rybakov-ks@ya.ru": "该工具可用于分析SEM图像中的粒度特征。<br>如遇图像分割问题或错误，请将资料发送至邮箱：rybakov-ks@ya.ru",
        "Анализ": "分析",
        "Изображение СЭМ": "SEM图像",
        "Результат сегментации": "分割结果",
        "Примеры": "示例",
        "Характеристики частицы": "粒子特征",
        "Анализировать": "分析",
        "Очистить": "清除",
        "Количество частиц": "粒子数量",
        "Статистика по частицам": "粒子统计",
        "Характеристики частиц": "粒子特性",
        "Файлы для скачивания": "可下载文件",
        "Графики распределения": "分布图表",
        "Вы удовлетворены качеством сегментации?": "您对分割质量满意吗?",
        "Да": "是",
        "Нет": "否",
        "Настройки": "设置",
        "Модель обнаружения": "检测模型",
        "Включить": "启用",
        "Включить обработку с разбиением на фрагменты (SAHI)?": "启用分块处理(SAHI)?",
        "Высота слайса": "切片高度",
        "Ширина слайса": "切片宽度",
        "Перекрытие по высоте": "高度重叠率",
        "Перекрытие по ширине": "宽度重叠率",
        "Точность обнаружения": "检测置信度阈值",
        "Порог перекрытия (IoU)": "IoU阈值",
        "Максимальное количество обнаружений": "最大检测数量",
        "Режим масштабирования": "缩放模式",
        "Разрешение изображения": "图像分辨率",
        "Округлять результаты до": "结果四舍五入至",
        "Включить режим анализа отдельных частиц?": "启用单粒子分析模式?",
        "Интервалов на гистограмме": "直方图区间数",
        "Ошибка: изображение отсутствует...": "错误：图片缺失...",
        "Используется CUDA устройство:": "CUDA 设备正在使用中：",
        "CUDA не доступна, используется CPU": "CUDA 不可用，正在占用 CPU",
        "Шкала прибора в мкм": "Instrument scale in µm",
        "Включить отображение диаметров Ферета?": "是否显示雪貂直径？",
        "Распределение диаметра Ферета": "費雷特直徑分佈",
        "Распределение угла Ферета": "費雷特角的分佈",
        "Векторное поле ориентации": "取向矢量场",
        "Удлинение": "伸长",
        "Утолщение": "加厚",
        "ИИ-интерпретация SEM-данных": "SEM数据的AI解读",
        "Запустить ИИ-анализ": "启动人工智能分析",
        "Языковая модель (LLM)": "语言模型（法学硕士）",
        "Готово!": "准备好！",
        "Длина шкалы в мкм": "比例尺长度（微米）",
        "Длина шкалы в нм": "比例尺长度（纳米）",
        "О программе": "关于",
        "Статистика": "统计数据",
        "Графики": "图表",
        "ИИ-анализ": "人工智能分析",
        "Файлы": "文件",
        "Оценить результаты": "评估结果",
        "Результаты сегментации частиц": "颗粒分割结果",
        "Отменить": "取消",
        about_ru: about_zh_cn,
        "ru": "'zh-cn'",
        "Помощь": "演出指南",
        "Как задать масштаб?": "如何设定比例？",
        "Справочник параметров": "参数参考",
        reference_ru: reference_zh_cn,
        """🔬 **Добро пожаловать в систему анализа SEM-изображений!**
        Я – ваш виртуальный ассистент в сканирующей электронной микроскопии. Готов провести детальный анализ морфологии и размерных характеристик частиц.""": """🔬 **欢迎使用扫描电镜图像分析系统！**
            我是您的电子显微镜虚拟助手，可对颗粒形貌和尺寸特征进行详细分析。""",
        "Видео инструкция": "视频说明",
        "Параметры фильтрации": "过滤选项",
        "Включить контур?": "启用轮廓？",
        "Цвет контура": "轮廓颜色",
        "Включить заливку?": "启用填充？",
        "Тип заливки": "填充类型",
        "Цвет заливки": "填充颜色",
        "Прозрачность заливки": "填充透明度",
        "Удалить частицы": "去除颗粒",
        "Сбросить таблицу": "重置表",
        "Загрузить изображение СЭМ": "上传扫描电镜图像",
        "Статус калибровки масштаба": "秤校准状态",
        "Выберите две крайние точки на шкале": "选择尺度的两个极值点。",
        "Расстояние равно": "距离",
        "пикселей": "像素",
        "Выбрано точек": "已选点",
        "Ориентация": "方向",
        "Количество обнаружений": "检测次数",
        "Настройки обнаружения": "发现设置",
        "Обработка с разбиением (SAHI)": "分区处理（SAHI）",
        "Основные параметры": "基本参数",
        "Параметры визуализации": "渲染选项",
        "Не поддерживаемый формат изображения.": "不支持的图像格式。",
        "Включить отображение масштабной шкалы?": "启用比例尺显示吗？",
        "Улучшение изображения": "图像增强",
        "RF-DETR обрабатывает изображение...": "RF-DETR 处理图像...",
        "Автоматическое определение масштабной шкалы не удалось. Укажите шкалу вручную или продолжите анализ в пикселях.": "自动比例检测失败。请手动指定比例或继续以像素为单位进行分析。",
        "Масштабная шкала обнаружена и распознана автоматически. Можно продолжить дальнейший анализ.": "比例尺已自动检测并识别。可以进行进一步分析。",
        "Включить автоматическое определение масштабной шкалы?": "启用自动体重检测？",
        "2D shape filtering": "2D 形状过滤",
        "Keep near-circular particles only": "仅保留近似圆形的颗粒",
        "Uses circularity and axis ratio as a 2D proxy for sphericity.": "使用圆形度和轴比作为球形度的二维近似。",
        "Minimum circularity": "最小圆形度",
        "Minimum axis ratio (minor/major)": "最小轴比（短轴/长轴）",
        "No particles matched the 2D shape filter. Lower the thresholds or disable the filter.": "没有颗粒通过 2D 形状过滤。请降低阈值或禁用过滤。",
        "Analyze nanorods": "分析纳米棒",
        "Measures rod length and width with orthogonal Feret calipers. Nanorod mode overrides the near-circular filter.": "使用正交 Feret 卡尺测量棒的长度和宽度。纳米棒模式优先于近圆形过滤。",
        "Minimum nanorod aspect ratio (L/W)": "最小纳米棒长宽比 (L/W)",
        "Length is the caliper span perpendicular to the minimum Feret width.": "长度是垂直于最小 Feret 宽度方向的卡尺跨度。",
        "Exclude border-touching rods": "排除接触图像边界的纳米棒",
        "Recommended because clipped rods bias aspect-ratio statistics.": "建议启用，因为被截断的纳米棒会使长宽比统计产生偏差。",
        "Border quality control": "边界质量控制",
        "Exclude border-touching particles": "排除接触图像边界的颗粒",
        "Applied independently of shape mode. Border-clipped particles bias size and aspect-ratio measurements.": "此设置独立于形状分析模式。被边界截断的颗粒会使尺寸和长宽比测量产生偏差。",
        "Manual contour editor": "手动轮廓编辑器",
        "Select a particle in the segmentation result before replacing or deleting it. For add or replace, click polygon vertices in order, then apply the contour.": "替换或删除前，请先在分割结果中选择颗粒。添加或替换时，请依次点击多边形顶点，然后应用轮廓。",
        "Choose Add or Replace to begin drawing.": "选择“添加”或“替换”以开始绘制。",
        "Contour editing canvas": "轮廓编辑画布",
        "Add new contour": "添加新轮廓",
        "Replace selected contour": "替换所选轮廓",
        "Delete selected particles": "删除所选颗粒",
        "Select at least one particle before deleting.": "删除前请至少选择一个颗粒。",
        "Undo last point": "撤销上一点",
        "Clear draft": "清除草稿",
        "Apply contour": "应用轮廓",
        "Run image analysis before editing contours.": "编辑轮廓前请先运行图像分析。",
        "Select exactly one particle before replacing its contour.": "替换轮廓前请仅选择一个颗粒。",
        "Click contour vertices in order, then choose Apply contour.": "请依次点击轮廓顶点，然后选择“应用轮廓”。",
        "Choose Add or Replace before drawing.": "绘制前请选择“添加”或“替换”。",
        "Choose Add or Replace before applying a contour.": "应用轮廓前请选择“添加”或“替换”。",
        "The selected point is outside the analysis image.": "所选点位于分析图像之外。",
        "Draft vertices: {count}": "草稿顶点数：{count}",
        "Draft cleared.": "草稿已清除。",
        "The contour touches the image border and was not applied because border exclusion is enabled.": "该轮廓接触图像边界；由于已启用边界排除，因此未应用。",
        "The contour could not be measured.": "无法测量该轮廓。",
        "A new contour was added and measured.": "已添加并测量新轮廓。",
        "The selected contour was replaced and remeasured.": "已替换并重新测量所选轮廓。",
        "Exclude likely merged/overlapping rods": "排除可能粘连或重叠的纳米棒",
        "Removes duplicate masks and oversized clusters while retaining smaller rod-like masks. Obscured rods are not reconstructed.": "移除重复掩膜和过大的团簇，同时保留较小的棒状掩膜；不会重建被遮挡的纳米棒。",
        "Excluded {count} likely merged or duplicate rod masks.": "已排除 {count} 个可能粘连或重复的纳米棒掩膜。",
        "Overlap quality control": "重叠质量控制",
        "Exclude likely merged/duplicate masks": "排除可能合并或重复的掩膜",
        "Applied independently of shape mode. Removes duplicate masks and unusually wide or irregular clusters; hidden particles are not reconstructed.": "此设置独立于形状分析模式。会移除重复掩膜以及异常宽大或不规则的团簇；不会重建被遮挡的颗粒。",
        "Excluded {count} likely merged or duplicate masks.": "已排除 {count} 个可能合并或重复的掩膜。",
        "No particles remained after overlap quality control. Disable overlap exclusion to inspect ambiguous masks.": "重叠质量控制后没有剩余颗粒。关闭重叠排除可检查不明确的掩膜。",
        "Overlap QC reached its comparison limit; some ambiguous masks may remain.": "重叠质量检查已达到比较上限；可能仍有一些不明确的掩膜。",
        "No nanorods matched the selected aspect-ratio and quality criteria. Lower the threshold or allow border-touching/merged rods.": "没有纳米棒符合所选长宽比和质量条件。请降低阈值，或允许接触边界及可能粘连的纳米棒。",
        "Nanorod aspect ratio (L/W)": "纳米棒长宽比 (L/W)",
        "ISO Feret ratio (min/max)": "ISO Feret 比率（最小/最大）",
        "Nanorod aspect ratio (L/W) distribution": "纳米棒长宽比 (L/W) 分布",
        "ISO Feret ratio (min/max) distribution": "ISO Feret 比率（最小/最大）分布",
        "Nanorod aspect-ratio chart": "纳米棒长宽比图表",
        "Aspect-ratio distribution": "长宽比分布",
        "Rod length versus width": "纳米棒长度与宽度",
        "Retained rods": "保留的纳米棒",
        "Individual rods": "单个纳米棒",
        "Interior rods": "图像内部纳米棒",
        "Border-touching rods": "接触边界的纳米棒",
        "Unknown border status": "边界状态未知",
        "Particle": "颗粒",
        "Rod orientation": "纳米棒方向",
        "Not available": "无数据",
        "Border touching": "接触边界",
        "Count": "数量",
        "Mean": "平均值",
        "Median": "中位数",
        "Minimum L/W": "最小 L/W",
        "Invalid rows": "无效行",
        "No nanorod measurements available.": "没有可用的纳米棒测量结果。",
        "Projected aspect ratio = orthogonal-caliper length / minimum-Feret width; it is dimensionless and describes a 2D projection.": "投影长宽比 = 正交卡尺长度 / 最小 Feret 宽度；该值无量纲并描述二维投影。",
        "Language settings": "语言设置",
        "Interface language": "界面语言",
        "Switches interface labels and future analysis results. The page reloads.": "切换界面标签和后续分析结果的语言。页面将重新加载。",
        "Automatic / Browser": "自动 / 浏览器",
        "No particles detected": "未检测到颗粒",
        "Analysis error": "分析错误",
    },
    "zh-tw": {
        "Подготовка...": "初始化中...",
        "Загрузка изображения...": "正在載入圖像...",
        "Instrument scale in µm": "Instrument scale in µm",
        "Pixels": "Pixels",
        "Original": "Original",
        "YOLO обрабатывает изображение...": "YOLO正在處理圖像...",
        "Ошибка: недостаточно памяти CUDA. Освобождаем память. Попробуйте уменьшить разрешение изображения или включите режим SAHI...": "錯誤：CUDA記憶體不足。正在釋放記憶體。請嘗試降低圖像解析度或啟用SAHI模式...",
        "Произошла другая ошибка": "發生其他錯誤",
        "Объекты не обнаружены.": "未檢測到對象",
        "Достигнут предел количества обнаружений. Увеличьте максимальное количество обнаружений в настройках.": "達到檢測數量上限。請在設定中增加最大檢測數量",
        "Обработка частиц...": "正在處理粒子...",
        "мкм": "微米",
        "нм": "奈米",
        "пикс": "像素",
        "ед.": "單位",
        "Диаметр": "直徑",
        "Средний диаметр": "平均直徑",
        "Максимальный диаметр": "最大直徑",
        "Минимальный диаметр": "最小直徑",
        "Максимальный угол": "最大角度",
        "Минимальный угол": "最小角度",
        "Площадь": "面積",
        "Периметр": "周長",
        "Detectron2 обрабатывает изображение...": "Detectron2正在處理圖像...",
        "Произошла ошибка:": "發生錯誤:",
        "SAHI обрабатывает изображение...": "SAHI 正在處理影像...",
        "Построение таблицы...": "正在生成表格...",
        "Параметр": "參數",
        "Среднее": "平均值",
        "Медиана": "中位數",
        "Максимум": "最大值",
        "Минимум": "最小值",
        "СО": "標準差",
        "Построение графиков...": "正在生成圖表...",
        "Распределение площади": "面積分布",
        "Распределение периметра": "周長分布",
        "Распределение диаметра": "直徑分布",
        "Распределение эксцентриситета": "偏心率分布",
        "Распределение интенсивности": "強度分布",
        "(норм. распр.)": "(正態分布)",
        "Количество": "數量",
        "Плотность вероятности": "概率密度",
        "Эксцентриситет": "偏心率",
        "Интенсивность": "強度",
        "Критическая ошибка в process_image": "process_image中的關鍵錯誤",
        "Критическая ошибка": "嚴重錯誤",
        "Ошибка в вычислении центроида.": "計算質心時出錯",
        "Найдено больше двух точек.": "找到超過兩個點",
        "Обозначьте на изображении масштабную шкалу при помощи двух точек.": "請在圖像上用兩點標記比例尺",
        "Тёмный режим": "暗黑模式",
        "Светлый режим": "明亮模式",
        "ParticleAnalyzer — Инструмент для анализа изображений SEM": "ParticleAnalyzer — SEM圖像分析工具",
        "Инструмент для анализа размерных характеристик частиц на изображениях SEM.<br>В случае проблем с сегментацией изображения или возникновения ошибок, пожалуйста, направляйте материалы на электронную почту: rybakov-ks@ya.ru": "此工具可用於分析SEM影像中的粒度特徵。 <br>如遇影像分割問題或錯誤，請將資料寄至信箱：rybakov-ks@ya.ru",
        "Анализ": "分析",
        "Изображение СЭМ": "SEM圖像",
        "Результат сегментации": "分割結果",
        "Примеры": "示例",
        "Характеристики частицы": "粒子特徵",
        "Анализировать": "分析",
        "Очистить": "清除",
        "Количество частиц": "粒子數量",
        "Статистика по частицам": "粒子統計",
        "Характеристики частиц": "粒子特性",
        "Файлы для скачивания": "可下載文件",
        "Графики распределения": "分布圖表",
        "Вы удовлетворены качеством сегментации?": "您對分割質量滿意嗎?",
        "Да": "是",
        "Нет": "否",
        "Настройки": "設定",
        "Модель обнаружения": "檢測模型",
        "Включить": "啟用",
        "Включить обработку с разбиением на фрагменты (SAHI)?": "啟用分塊處理(SAHI)?",
        "Высота слайса": "切片高度",
        "Ширина слайса": "切片寬度",
        "Перекрытие по высоте": "高度重疊率",
        "Перекрытие по ширине": "寬度重疊率",
        "Точность обнаружения": "檢測置信度閾值",
        "Порог перекрытия (IoU)": "IoU閾值",
        "Максимальное количество обнаружений": "最大檢測數量",
        "Режим масштабирования": "縮放模式",
        "Разрешение изображения": "圖像解析度",
        "Округлять результаты до": "結果四捨五入至",
        "Включить режим анализа отдельных частиц?": "啟用單粒子分析模式?",
        "Интервалов на гистограмме": "直方圖區間數",
        "Ошибка: изображение отсутствует...": "錯誤：圖片缺失...",
        "Используется CUDA устройство:": "CUDA 設備正在使用中：",
        "CUDA не доступна, используется CPU": "CUDA 不可用，正在佔用 CPU",
        "Шкала прибора в мкм": "Instrument scale in µm",
        "Включить отображение диаметров Ферета?": "是否顯示雪貂直徑？",
        "Распределение диаметра Ферета": "費雷特直徑分佈",
        "Распределение угла Ферета": "費雷特角的分佈",
        "Средний диаметр [мкм]": "平均直徑[微米]",
        "Максимальный диаметр [мкм]": "最大直徑[微米]",
        "Минимальный диаметр [мкм]": "最小直徑[微米]",
        "Средний диаметр [пикс]": "平均直徑[像素]",
        "Максимальный диаметр [пикс]": "最大直徑[像素]",
        "Минимальный диаметр [пикс]": "最小直徑[像素]",
        "Максимальный угол [°]": "最大角度[°]",
        "Минимальный угол [°]": "最小角度[°]",
        "Векторное поле ориентации": "取向向量場",
        "Удлинение": "伸長",
        "Утолщение": "加厚",
        "ИИ-интерпретация SEM-данных": "SEM數據的AI解讀",
        "Запустить ИИ-анализ": "啟動人工智慧分析",
        "Языковая модель (LLM)": "語言模型（法學碩士）",
        "Готово!": "準備好！",
        "Длина шкалы в мкм": "比例尺長度（微米）",
        "Длина шкалы в нм": "比例尺長度（納米）",
        "О программе": "關於",
        "Статистика": "統計數據",
        "Графики": "圖表",
        "ИИ-анализ": "人工智慧分析",
        "Файлы": "檔案",
        "Оценить результаты": "評估結果",
        "Результаты сегментации частиц": "粒子分割結果",
        "Отменить": "取消",
        about_ru: about_zh_tw,
        "ru": "'zh-tw'",
        "Помощь": "演出指南",
        "Как задать масштаб?": "如何設定比例？",
        "Справочник параметров": "參數參考",
        reference_ru: reference_zh_tw,
        """🔬 **Добро пожаловать в систему анализа SEM-изображений!**
        Я – ваш виртуальный ассистент в сканирующей электронной микроскопии. Готов провести детальный анализ морфологии и размерных характеристик частиц.""": """🔬 **歡迎使用掃描式電子顯微鏡影像分析系統！**
            我是您的電子顯微鏡虛擬助手，可對顆粒形貌和尺寸特徵進行詳細分析。""",
        "Видео инструкция": "影片說明",
        "Параметры фильтрации": "過濾選項",
        "Включить контур?": "啟用輪廓？",
        "Цвет контура": "輪廓顏色",
        "Включить заливку?": "啟用填充？",
        "Тип заливки": "填滿類型",
        "Цвет заливки": "填滿顏色",
        "Удалить частицы": "去除顆粒",
        "Сбросить таблицу": "重設表",
        "Загрузить изображение СЭМ": "上傳掃描電子顯微鏡影像",
        "Статус калибровки масштаба": "秤校準狀態",
        "Выберите две крайние точки на шкале": "選擇尺度的兩個極值點。",
        "Расстояние равно": "距離",
        "пикселей": "像素",
        "Выбрано точек": "已選點",
        "Ориентация": "方向",
        "Количество обнаружений": "檢測次數",
        "Настройки обнаружения": "發現設定",
        "Обработка с разбиением (SAHI)": "分區處理（SAHI）",
        "Основные параметры": "基本參數",
        "Параметры визуализации": "渲染選項",
        "Не поддерживаемый формат изображения.": "不支援的圖像格式。",
        "Включить отображение масштабной шкалы?": "啟用比例尺顯示嗎？",
        "Улучшение изображения": "影像增強",
        "RF-DETR обрабатывает изображение...": "RF-DETR 處理影像...",
        "Автоматическое определение масштабной шкалы не удалось. Укажите шкалу вручную или продолжите анализ в пикселях.": "自動比例檢測失敗。請手動指定比例或繼續以像素為單位進行分析。",
        "Масштабная шкала обнаружена и распознана автоматически. Можно продолжить дальнейший анализ.": "比例尺已自動偵測並識別。可以進行進一步分析。",
        "Включить автоматическое определение масштабной шкалы?": "啟用自動體重偵測？",
        "2D shape filtering": "2D 形狀過濾",
        "Keep near-circular particles only": "僅保留近似圓形的顆粒",
        "Uses circularity and axis ratio as a 2D proxy for sphericity.": "使用圓形度和軸比作為球形度的二維近似。",
        "Minimum circularity": "最小圓形度",
        "Minimum axis ratio (minor/major)": "最小軸比（短軸/長軸）",
        "No particles matched the 2D shape filter. Lower the thresholds or disable the filter.": "沒有顆粒通過 2D 形狀過濾。請降低閾值或停用過濾。",
        "Analyze nanorods": "分析奈米棒",
        "Measures rod length and width with orthogonal Feret calipers. Nanorod mode overrides the near-circular filter.": "使用正交 Feret 卡尺測量棒的長度和寬度。奈米棒模式優先於近圓形過濾。",
        "Minimum nanorod aspect ratio (L/W)": "最小奈米棒長寬比 (L/W)",
        "Length is the caliper span perpendicular to the minimum Feret width.": "長度是垂直於最小 Feret 寬度方向的卡尺跨度。",
        "Exclude border-touching rods": "排除接觸影像邊界的奈米棒",
        "Recommended because clipped rods bias aspect-ratio statistics.": "建議啟用，因為被截斷的奈米棒會使長寬比統計產生偏差。",
        "Border quality control": "邊界品質控制",
        "Exclude border-touching particles": "排除接觸影像邊界的顆粒",
        "Applied independently of shape mode. Border-clipped particles bias size and aspect-ratio measurements.": "此設定獨立於形狀分析模式。被邊界截斷的顆粒會使尺寸和長寬比測量產生偏差。",
        "Manual contour editor": "手動輪廓編輯器",
        "Select a particle in the segmentation result before replacing or deleting it. For add or replace, click polygon vertices in order, then apply the contour.": "替換或刪除前，請先在分割結果中選擇顆粒。新增或替換時，請依序點選多邊形頂點，然後套用輪廓。",
        "Choose Add or Replace to begin drawing.": "選擇「新增」或「替換」以開始繪製。",
        "Contour editing canvas": "輪廓編輯畫布",
        "Add new contour": "新增輪廓",
        "Replace selected contour": "替換所選輪廓",
        "Delete selected particles": "刪除所選顆粒",
        "Select at least one particle before deleting.": "刪除前請至少選擇一個顆粒。",
        "Undo last point": "復原上一點",
        "Clear draft": "清除草稿",
        "Apply contour": "套用輪廓",
        "Run image analysis before editing contours.": "編輯輪廓前請先執行影像分析。",
        "Select exactly one particle before replacing its contour.": "替換輪廓前請僅選擇一個顆粒。",
        "Click contour vertices in order, then choose Apply contour.": "請依序點選輪廓頂點，然後選擇「套用輪廓」。",
        "Choose Add or Replace before drawing.": "繪製前請選擇「新增」或「替換」。",
        "Choose Add or Replace before applying a contour.": "套用輪廓前請選擇「新增」或「替換」。",
        "The selected point is outside the analysis image.": "所選點位於分析影像之外。",
        "Draft vertices: {count}": "草稿頂點數：{count}",
        "Draft cleared.": "草稿已清除。",
        "The contour touches the image border and was not applied because border exclusion is enabled.": "該輪廓接觸影像邊界；由於已啟用邊界排除，因此未套用。",
        "The contour could not be measured.": "無法測量該輪廓。",
        "A new contour was added and measured.": "已新增並測量新輪廓。",
        "The selected contour was replaced and remeasured.": "已替換並重新測量所選輪廓。",
        "Exclude likely merged/overlapping rods": "排除可能黏連或重疊的奈米棒",
        "Removes duplicate masks and oversized clusters while retaining smaller rod-like masks. Obscured rods are not reconstructed.": "移除重複遮罩和過大的團簇，同時保留較小的棒狀遮罩；不會重建被遮擋的奈米棒。",
        "Excluded {count} likely merged or duplicate rod masks.": "已排除 {count} 個可能黏連或重複的奈米棒遮罩。",
        "Overlap quality control": "重疊品質控制",
        "Exclude likely merged/duplicate masks": "排除可能合併或重複的遮罩",
        "Applied independently of shape mode. Removes duplicate masks and unusually wide or irregular clusters; hidden particles are not reconstructed.": "此設定獨立於形狀分析模式。會移除重複遮罩以及異常寬大或不規則的團簇；不會重建被遮擋的顆粒。",
        "Excluded {count} likely merged or duplicate masks.": "已排除 {count} 個可能合併或重複的遮罩。",
        "No particles remained after overlap quality control. Disable overlap exclusion to inspect ambiguous masks.": "重疊品質控制後沒有剩餘顆粒。關閉重疊排除可檢查不明確的遮罩。",
        "Overlap QC reached its comparison limit; some ambiguous masks may remain.": "重疊品質檢查已達到比較上限；可能仍有一些不明確的遮罩。",
        "No nanorods matched the selected aspect-ratio and quality criteria. Lower the threshold or allow border-touching/merged rods.": "沒有奈米棒符合所選長寬比和品質條件。請降低閾值，或允許接觸邊界及可能黏連的奈米棒。",
        "Nanorod aspect ratio (L/W)": "奈米棒長寬比 (L/W)",
        "ISO Feret ratio (min/max)": "ISO Feret 比率（最小/最大）",
        "Nanorod aspect ratio (L/W) distribution": "奈米棒長寬比 (L/W) 分布",
        "ISO Feret ratio (min/max) distribution": "ISO Feret 比率（最小/最大）分布",
        "Nanorod aspect-ratio chart": "奈米棒長寬比圖表",
        "Aspect-ratio distribution": "長寬比分布",
        "Rod length versus width": "奈米棒長度與寬度",
        "Retained rods": "保留的奈米棒",
        "Individual rods": "單個奈米棒",
        "Interior rods": "影像內部奈米棒",
        "Border-touching rods": "接觸邊界的奈米棒",
        "Unknown border status": "邊界狀態未知",
        "Particle": "顆粒",
        "Rod orientation": "奈米棒方向",
        "Not available": "無資料",
        "Border touching": "接觸邊界",
        "Count": "數量",
        "Mean": "平均值",
        "Median": "中位數",
        "Minimum L/W": "最小 L/W",
        "Invalid rows": "無效列",
        "No nanorod measurements available.": "沒有可用的奈米棒測量結果。",
        "Projected aspect ratio = orthogonal-caliper length / minimum-Feret width; it is dimensionless and describes a 2D projection.": "投影長寬比 = 正交卡尺長度 / 最小 Feret 寬度；此值無量綱並描述二維投影。",
        "Language settings": "語言設定",
        "Interface language": "介面語言",
        "Switches interface labels and future analysis results. The page reloads.": "切換介面標籤和後續分析結果的語言。頁面將重新載入。",
        "Automatic / Browser": "自動 / 瀏覽器",
        "No particles detected": "未偵測到顆粒",
        "Analysis error": "分析錯誤",
        "Прозрачность заливки": "填充透明度",
    },
}

i18n = gr.I18n(
    ru=translations["ru"],
    en=translations["en"],
    **{"zh-CN": translations["zh-cn"], "zh-TW": translations["zh-tw"]},
)
